### ISSUE TITLE
Implement the page-footer links into the navbar

### ISSUE THREAD

**Issue by AlishChhetri** [TeamDevDev/www.developerdevelopment.com#27]
The links provided in the page-footer should also be included on the right side of the nav bar. To implement this feature, add the following to the navbar portion of the _quarto.yml file:

```
    right:
      - text: "{{< iconify fa github size=18px >}}"
        href: https://github.com/TeamDevDev/
      - text: "{{< iconify fa github-square size=18px >}}"
        href: https://github.com/TeamDevDev/www.developerdevelopment.com/
      - text: "{{< iconify bi discord size=19px >}}"
        href: https://discord.gg/aNfn8DNEMx
      - text: "{{< iconify bi rss-fill size=18px >}}"
        href: "blog/index.xml"
```
